language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
  - yarn

script:
  - yarn run build:demo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: demo
  on:
    branch: master
